import type { Project } from './types';

export const projects: Project[] = [
  {
    slug: 'doctag',
    title: 'Doctag',
    oneLiner: 'App desktop de tagging de documentos. [placeholder]',
    tags: ['Electron', 'React', 'PostgreSQL'],
    role: 'Criador e único desenvolvedor',
    previewVideo: '/videos/doctag-preview.mp4',
    narrative: [
      '[placeholder] Doctag é um app desktop para organizar documentos por tags, com um banco Postgres embutido — sem servidor externo.',
      '[placeholder] O maior desafio foi o drag-and-drop de tags continuar acessível por teclado, sem perder a fluidez do mouse.',
      '[placeholder] Construído com Electron + React, com foco em uma experiência rápida mesmo com milhares de documentos indexados.',
    ],
    demoIndex: 0,
    demo: { type: 'mock', component: 'doctag' },
    links: { github: 'https://github.com/placeholder/doctag' },
  },
  {
    slug: 'graphit',
    title: 'GraphIt',
    oneLiner: 'Ferramenta de grafos e visualização. [placeholder]',
    tags: ['React', 'Vite'],
    role: 'Criador e único desenvolvedor',
    previewVideo: '/videos/graphit-preview.mp4',
    narrative: [
      '[placeholder] GraphIt é uma ferramenta para desenhar e explorar grafos, migrando de HTML vanilla para React + Vite.',
      '[placeholder] A reescrita trouxe um modelo de estado mais previsível para desenhar nós e arestas interativamente.',
    ],
    demoIndex: 1,
    demo: { type: 'mock', component: 'graphit' },
    links: { github: 'https://github.com/placeholder/graphit' },
  },
  {
    slug: 'hcp-app',
    title: 'HCP App',
    oneLiner: 'Sistema de produção para gestão de processos. [placeholder]',
    tags: ['FastAPI', 'React'],
    role: 'Engenheiro de software',
    previewVideo: '/videos/hcp-app-placeholder.mp4',
    narrative: [
      '[placeholder] HCP App é um sistema interno de produção construído com FastAPI no backend e React no frontend.',
      '[placeholder] Sem mock interativo aqui — a demo é em vídeo, já que o sistema depende de dados internos da empresa.',
    ],
    demoIndex: 0,
    demo: { type: 'video', src: '/videos/hcp-app-placeholder.mp4' },
  },
  {
    slug: 'valentines',
    title: 'Valentines',
    oneLiner: 'Site personalizado para o Dia dos Namorados. [placeholder]',
    tags: ['Vercel', 'React'],
    role: 'Criador e único desenvolvedor',
    previewVideo: '/videos/valentines-preview.mp4',
    narrative: [
      '[placeholder] Valentines é um modelo de site para o Dia dos Namorados com foco na interação do usuário.',
      '[placeholder] As seções apresentam elementos interativos e a UI/UX foi planejada para ser chamativa e divertida.',
    ],
    demoIndex: 0,
    demo: { type: 'video', src: '/videos/valentines-preview.mp4' },
  },
  {
    slug: 'cablagem',
    title: 'Cablagem',
    oneLiner: 'Automação para contagem de materiais e orçamento de chicotes. [placeholder]',
    tags: ['Google Apps Script', 'Google Sheets'],
    role: 'Engenheiro de software',
    previewVideo: '/videos/cablagem-placeholder.mp4',
    narrative: [
      '[placeholder] Cablagem é um script de Google Apps Script acoplado a uma planilha, que consolida quantitativos de materiais, conectores, luvas, etiquetas e abraçadeiras a partir do comprimento dos cabos.',
      '[placeholder] Sem mock interativo aqui — a demo é em vídeo, já que o script depende de planilhas e templates internos da HCP.',
    ],
    demoIndex: 0,
    demo: { type: 'video', src: '/videos/cablagem-placeholder.mp4' },
  },
  {
    slug: 'cotacao',
    title: 'Cotação',
    oneLiner: 'Extrator de dados de chicotes elétricos a partir de PDFs com IA. [placeholder]',
    tags: ['Flask', 'React', 'Gemini API'],
    role: 'Engenheiro de software',
    previewVideo: '/videos/cotacao-placeholder.mp4',
    narrative: [
      '[placeholder] Cotação é um app desktop (Flask + React) que extrai dados de chicotes elétricos a partir de PDFs usando a API do Gemini, com histórico de cotações em um banco local.',
      '[placeholder] Sem mock interativo aqui — a demo é em vídeo, já que o app depende de PDFs e dados internos da HCP.',
    ],
    demoIndex: 0,
    demo: { type: 'video', src: '/videos/cotacao-placeholder.mp4' },
  },
];
